### ISSUE TITLE
Story: Keyword Search (/search URL)

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/glossary-app#14]
##  As a user, I would like to be able to enter keywords and have the option to submit a search

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: User enters /search in the URL (so URL looks like /publications/dictionaries/cancer-terms/search) and tries to access the dictionary
Given user has entered /publications/dictionaries/cancer-terms/search in the URL
  When user tries to go to this URL, system should return the "No Matches Found" page
```

```gherkin
Background
  Given language is set to "es"
Scenario: User enters /buscar in the URL (so URL looks like /espanol/publicaciones/diccionario/buscar ) and tries to access the dictionary
Given user has entered espanol/publicaciones/diccionario/buscar in the URL
  When user tries to go to this URL, system should return the spanish "No Matches Found" page
```

```gherkin
Scenario: User is able to enter keywords for a search
Given user is on a dictionary landing page 
  Then search bar is displayed below introductory text 
    And search bar contains a placeholder text “Enter keywords or phrases” 
    And “Search” button is displayed 
  When user starts typing in the search bar 
  Then placeholder text disappears  
  And user is able to click "Search" to submit their search
  Then the system returns search results page for the search term (URL has /search)
  And the page displays the following label above the results: “# results found for: <word or phrase>"
    And each result in the results listing appears as a link to the term’s page 
    And the audio icon appears beside the term on the same line as the link
    And the pronunciation appears beside the audio icon 
    And each result displays its full definition below the link for the term 
```

```gherkin
Background
  Given "language" is set to "es"
Scenario: User is able to enter keywords with accents for a search
Given user is on the Spanish dictionary landing page 
  Then search bar is displayed below introductory text 
  And search bar contains a placeholder text “Escriba frase o palabra clave” 
  And user is able to enter special characters
    Examples:  |characters| 
When user starts typing in the search bar 
  Then placeholder text disappears  
  And user is able to click "Buscar" to submit their search
  Then the system returns users to the search results page for the search term (URL has /buscar)
  And the page displays the following label above the results: “# resultados de:  <word or phrase>"
    And each result in the results listing appears as a link to the term’s page 
    And the audio icon appears beside the term on the same line as the link
    And each result displays its full definition below the link for the term 
```

```gherkin
Scenario: User executes a "starts with" search after entering terms.
  Given user is on landing Cancer Terms page 
  Then “Starts with” and “Contains” options are displayed 
    And “Starts with” is selected by default 
  When user starts typing <cancer> in the search bar 
    And user clicks on Search button 
  Then Search is executed  
  Then the system returns users to the search results page for the search term (URL has /search)
    And page displays “# results found for:” <cancer>  
    And List of results is displayed 
    And “Starts with” is selected by default 
    And search bar contains the <word> that user entered  
```

```gherkin
Background
  Given "language" is set to "es"
Scenario: User executes a "starts with" search after entering terms.
  Given user is on landing Cancer Terms page 
  Then “Empieza con” and “Contiene” options are displayed 
    And “Empieza con” is selected by default 
  When user starts typing <cancer> in the search bar 
    And user clicks on Buscar button 
  Then Search is executed  
  Then the system returns users to the search results page for the search term (URL has /buscar)
    And page displays “# resultados de:” <cancer>  
    And List of results is displayed 
    And "Empieza con” is selected by default 
    And search bar contains the <word> that user entered  
```

```gherkin
Scenario: User executes a "contains" search after entering terms.
  Given user is on landing Cancer Terms page 
  Then “Starts with” and “Contains” options are displayed 
    And “Starts with” is selected by default 
  Then user selects Contains option
  Then user starts typing "cancer" in the search bar 
    And user clicks on Search button 
  Then Search is executed  
  Then the system returns users to the search results page for the search term (URL has /search)
    And page displays “# results found for:” cancer
    And List of results is displayed 
    And “Contains” remains selected 
    And search bar contains the word "cancer" that user entered  
```

```gherkin
Background
  Given "language" is set to "es"
Scenario: User executes a "contains" search after entering terms.
  Given user is on landing Cancer Terms page 
  Then “Empieza con” and “Contiene” options are displayed 
    And “Empieza con” is selected by default 
  Then user selects Contiene option
  Then user starts typing "cancer" in the search bar 
    And user clicks on Buscar button 
  Then Search is executed  
  Then the system returns users to the search results page for the search term (URL has /buscar)
    And page displays “# resultados de:” cancer
    And List of results is displayed 
    And “Contiene” remains selected 
    And search bar contains the word "cancer" that user entered  
```

```gherkin
Scenario: User enters a keyword or phrase that does not generate any matches
 Given user is on Dictionary of Cancer Terms landing page
 When user enters "chicken pot pie" in the keyword box
 Then Search is executed  
    Then the page displays “No matches were found for the word or phrase you entered. Please check your spelling, and try searching again. You can also type the first few letters of your word or phrase, or click a letter in the alphabet and browse through the list of terms that begin with that letter."
```

```gherkin
Background
  Given language is set to "es"
Scenario: User enters a keyword or phrase that does not generate any matches in Spanish
 Given user is on Diccionario de cancer landing page
 When user enters "chicken" in the keyword box
 Then Search is executed  
    Then the page displays “No se encontraron resultados para lo que usted busca. Revise si escribió correctamente e inténtelo de nuevo. También puede escribir las primeras letras de la palabra o frase que busca o hacer clic en la letra del alfabeto y revisar la lista de términos que empiezan con esa letra."
```

```gherkin
Scenario: Search page metadata
  Given the user is viewing a search result page
  Then <meta name="robots" content="noindex" /> exists in the data for the page (URLs of /search or /buscar should all be noindex)
```

### Resources:
* Feature: https://tracker.nci.nih.gov/browse/CGOVWCMS-30

### Notes
- This will not display results, result display is a separate story.  This is just for the basic input box (with no options to switch between starts with or contains) 

---

### Tasks
- [X] Create basic search page with Search Box (no autosuggest), "Starts with" button, "Contains" button, and clickable A-Z list
- [ ] Create display for results list item 
- [ ] Create results list view
- [ ] Fetch result from API
- [ ] Ensure that "robots:noindex" is added to the /search and /buscar URLs
- [ ] Build results page for "No Terms matching search" message 
- [x] Write automated tests

### Technical Notes
- More notes, or technical nuances/direction
