### ISSUE TITLE
Story: 404 - Page Not Found

### ISSUE THREAD

**Issue by seyilonge-nci** [NCIOCPL/glossary-app#148]
## As a user, if I visit the definition page with a pretty url name that doesn't exist, I should be presented with a page indicating that my link could be bad

> **ESTIMATE** 5

### Acceptance Criteria

```gherkin
Scenario: Page not found should be displayed when a user visits the definition page with a pretty url that doesn't exist
    Given the user is viewing the definition with the pretty url "chicken"
     Then page title on error page is "Page Not Found"
      And the following links and texts exist on the page
      | https://www.cancer.gov         | homepage     | 
      | https://www.cancer.gov/types   | cancer type  | 
      | https://www.cancer.gov/contact | Get in touch | 
  
  Background: 
    Given "language" is set to "es"
  
  Scenario: Page not found should be displayed when a user visits the definition page with a pretty url that doesn't exist
    Given the user is viewing the definition with the pretty url "pollo"
     Then page title on error page is "No se encontró la página"
      And the following links and texts exist on the page
      | https://www.cancer.gov/espanol             | página principal | 
      | https://www.cancer.gov/espanol/tipos       | tipo de cáncer   | 
      | https://www.cancer.gov/espanol/contactenos | Contáctenos      | 
```
**Analytics**
```gherkin
Scenario: Page Load Analytics fires for a 404 on the terms page
    Given "audience" is set to "Patient"
      And "dictionaryTitle" is set to "NCI Dictionary of Cancer Terms"
      And "dictionaryName" is set to "Cancer.gov"
      And "language" is set to "en"
      And "baseHost" is set to "http://localhost:3000"
      And "canonicalHost" is set to "https://www.cancer.gov"
      And "siteName" is set to "National Cancer Institute"
      And "analyticsChannel" is set to "Publications"
      And "analyticsPublishedDate" is set to "02/02/2011"
     When the user is viewing the definition with the pretty url "chicken"
      And page title on error page is "Page Not Found"
      And browser waits
     Then there should be an analytics event with the following details
      | key                                    | value                          | 
      | type                                   | PageLoad                       | 
      | event                                  | GlossaryApp:Load:PageNotFound  | 
      | page.audience                          | Patient                        | 
      | page.channel                           | Publications                   | 
      | page.language                          | english                        | 
      | page.metaTitle                         | Page Not Found                 | 
      | page.name                              | www.cancer.gov/def/chicken     | 
      | page.title                             | Page Not Found                 | 
      | page.type                              | nciAppModulePage               | 
      | page.contentGroup                      | NCI Dictionary of Cancer Terms | 
      | page.publishedDate                     | 02/02/2011                     | 
      | page.additionalDetails.analyticsName   | CancerTerms                    | 
      | page.additionalDetails.dictionaryTitle | NCI Dictionary of Cancer Terms | 
      | page.additionalDetails.idOrName        | chicken                        | 
  
  Scenario: Page Load Analytics fires for a 404 on the spanish terms page
    Given "audience" is set to "Patient"
      And "dictionaryTitle" is set to "Diccionario de cáncer"
      And "dictionaryName" is set to "Cancer.gov"
      And "language" is set to "es"
      And "baseHost" is set to "http://localhost:3000"
      And "canonicalHost" is set to "https://www.cancer.gov"
      And "siteName" is set to "Instituto Nacional del Cáncer"
      And "analyticsChannel" is set to "Publications - Spanish"
      And "analyticsPublishedDate" is set to "02/02/2011"
     When the user is viewing the definition with the pretty url "pollo"
      And page title on error page is "No se encontró la página"
      And browser waits
     Then there should be an analytics event with the following details
      | key                                    | value                         | 
      | type                                   | PageLoad                      | 
      | event                                  | GlossaryApp:Load:PageNotFound | 
      | page.audience                          | Patient                       | 
      | page.channel                           | Publications - Spanish        | 
      | page.language                          | spanish                       | 
      | page.metaTitle                         | No se encontró la página      | 
      | page.name                              | www.cancer.gov/def/pollo      | 
      | page.title                             | No se encontró la página      | 
      | page.type                              | nciAppModulePage              | 
      | page.contentGroup                      | Diccionario de cáncer         | 
      | page.publishedDate                     | 02/02/2011                    | 
      | page.additionalDetails.analyticsName   | CancerTerms                   | 
      | page.additionalDetails.dictionaryTitle | Diccionario de cáncer         | 
      | page.additionalDetails.idOrName        | pollo                         | 
```

### Resources:
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: https://www.cancer.gov/publications/dictionaries/cancer-terms/def/proceso-neoplasico

### Notes
* So anything outside of the App routes should be handled by Drupal for an actual 404. so that means that a "404" in the app should only happen for:
  1. On the real web site a definition is not actually found.
  2. On react app dev someone asks for a route not within the app.

---

### Tasks
- [x] Create 404 page
- [x] Update `ErrorBoundary` component to display 404 page for 404 errors
- [x] Update unit tests for `ErrorBoundary` and `Definition` components
- [x] Integration tests
- [x] Analytics
- [x] Add Meta Tags

### Technical Notes
- More notes, or technical nuances/direction

**Comment by seyilonge-nci** [comment]
@blilianyu
Please can you provide your input here. Would like to know if this requires a mockup or we would be going with what we currently have in production [here](https://www.cancer.gov/publications/dictionaries/cancer-terms/def/proceso-neoplasico). Thanks

**Comment by blilianyu** [comment]
@seyilonge-nci The 404 page should be the same as production.

**Comment by blilianyu** [comment]
@seyilonge-nci Can we make the 404 to be the same as this on prod for Dictionary with the left nav? https://www.cancer.gov/about-cancer/understanding/404

If the URL is /publications/dictionaries/cancer-terms/def/....., we show the English message
If the URL is /espanol/publicaciones/diccionario/def.... we show the Spanish message

Please let me know if you'd like comps. Thanks!

**Comment by seyilonge-nci** [comment]
@blilianyu Got it! Thanks. Comps won't be needed, I'll just mold it after the current production page.

**Comment by seyilonge-nci** [comment]
@blilianyu 
I'll need the Spanish text as well.
Are we stripping out the Search box from the page?

**Comment by blilianyu** [comment]
@seyilonge-nci For Spanish it would be like this page https://www.cancer.gov/espanol/cancer/naturaleza/404.

Yes, the search at the bottom should be like the ones on prod without a heading.

**Comment by seyilonge-nci** [comment]
> @seyilonge-nci For Spanish it would be like this page https://www.cancer.gov/espanol/cancer/naturaleza/404.
> 
> Yes, the search at the bottom should be like the ones on prod without a heading.

👍

**Comment by seyilonge-nci** [comment]
@blilianyu The functionality here is slightly different. The page display after results are returned is different, so are the results as well. Looks like it's doing a full text search. 
@bryanpizzillo any ideas as to stripping, keeping or doing something different here?

**Comment by blilianyu** [comment]
@seyilonge-nci I think we would want it to be only for dictionary terms. @VictoriaSunNIH?

**Comment by VictoriaSunNIH** [comment]
Looks good - I can't test spanish right now, but assume that works as expected (because the def URL is the same for english and spanish.)

**Comment by blilianyu** [comment]
Looks good to me too but same issue as Victoria for Spanish.
