### ISSUE TITLE
Story: Basic Term Page

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/glossary-app#15]
## As a user, I would like to view basic definition information, so that I may be more informed about cancer related terms.

> **ESTIMATE** 3

### Acceptance Criteria

```gherkin
Scenario: As a user, I would like to see the basic information I am viewing the definition for
  Given the user is viewing the definition with the pretty url "metastatic"
  Then the page title is "metastatic"
  Then the pronunciation text "(meh-tuh-STA-tik)" appears on the page
  And the definition text "Having to do with metastasis, which is the spread of cancer from the primary site (place where it started) to other places in the body." appears on the page
```
```gherkin
Scenario: As a user, I would like to see the basic information for a Spanish term when I am viewing the definition for
  Given the user is viewing the definition with the pretty url "metastasico"
  Then the page title is "metastásico"
  Then there is no pronunciation text on the page
  And the definition text "Relacionado con la metástasis,\nque es la diseminación del cáncer desde el sitio primario\n(el lugar donde empezó) hasta otras partes del\ncuerpo." appears on the page
```

```gherkin

Scenario: negative: As a user, I see definition of term I am viewing and do not see the pronunciation text where it is not provided
  Given the user is viewing the definition with the pretty url "hpv"
 Then the page title is "hpv"
  Then the pronunciation text does not appear on the page
 And the definition text "A type of virus that can cause abnormal tissue growth (for example, warts) and other changes to cells. Infection for a long time with certain types of HPV can cause cervical cancer. HPV may also play a role in some other types of cancer, such as anal, vaginal, vulvar, penile, and oropharyngeal cancers. Also called human papillomavirus." appears on the page
```

```gherkin
Scenario: As a CDR manager, I would like to be able to find the CDRID of a definition on the definition page so that I can quickly locate the definition within the CDR system.
  Given the user is viewing the definition with the pretty url "metastatic"
  Then there should be a "data-cdr-id" attribute on the definition's title element
```

### Resources:
* Comp: https://publicis.invisionapp.com/share/HZVRID6RSJ7
* Web Page: https://www.cancer.gov/publications/dictionaries/cancer-terms/def/metastatic

### Notes

* The pronunciation text is optional
* For CDR ID - this was an agreed upon solution to the fact that we no longer display the cdrid in the url for terms anymore. This caused an issue when the editors needed to be able to find the ID of a definition that needed updating.
---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [x] Add `axios` library ( #57 )
- [x] Create Definition View component ( #61 )
- [ ] Fetch term definition from the API ( #65 )
- [x] E2E test

### Technical Notes
- More notes, or technical nuances/direction

**Comment by kate-mashkina** [comment]
@bryanpizzillo I updated both scenarios to be more specific which text it is referring to - definition text implementation will be different from pronunciation text, and I think it also gives clearer instructions
