### ISSUE TITLE
Update Cypress version

### ISSUE THREAD

**Issue by seyilonge-nci** [NCIOCPL/glossary-app#167]
*Update Cypress version from 3.8.3 to 4.8.0*

### Sub-Tasks
- [x] Update Cypress version 
- [x] Run tests locally
- [x] Run test in build environment

### Notes

*Some complementary notes if necessary:*
We've been having issues recently with some PR that fail during a build with an error about visibility of some elements as shown in the screenshot below:
<img width="1163" alt="Screen Shot 2020-06-15 at 9 51 57 AM" src="https://user-images.githubusercontent.com/58226882/84665615-0787a100-aeee-11ea-9ff1-d2d04b975569.png">

A little digging shows this issue is related to either browser version or Cypress version
https://github.com/cypress-io/cypress/issues/2037

Local instances running Cypress version 4.8.0 were either not running into the same issue or gave a better error message as to what Cypress seemed to have an issue with.

Change Log: https://docs.cypress.io/guides/references/changelog.html#4-8-0

**Comment by arcepaul** [comment]
Running `npm outdated` shows that we are a major and several minor versions behind.  Kate has been running the latest version and hasn't had some of the test fragility issues that we've been seeing pop up in pipelines.  There is also an update to cypress-cucumber-preprocessor that should be brought in.
