### ISSUE TITLE
Story: Search Results Display

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/glossary-app#20]
## As a user, I would like to view my results from a search, along with links to the term’s page and the definition of the term. 

> **ESTIMATE** 3

### Acceptance Criteria

```gherkin
Scenario: User has executed a search and is viewing the results listing
Given user has executed a search in the Dictionary 
  Then page displays “# results found for: [term]”  
  And each result in the listing appears as a link to the term’s page 
  And each result displays its full definition below the link for the term 
```

### Resources:
* Feature: https://tracker.nci.nih.gov/browse/CGOVWCMS-30
* Web Page: https://www.cancer.gov/publications/dictionaries/cancer-terms/search?contains=false&q=cancer

### Notes

---

### Prerequisites
- [ ] Create a shared component for results item look and feel

### Tasks
- [ ] Fetch results from API
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
Closing this, it is rolled into larger stories for /expand and /results
