### ISSUE TITLE
Story: Analytics - Other - Results Click within Search

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/glossary-app#21]
## As an analyst, I would like to capture analytics when a user clicks on a result within a dictionary search to take them to a definition page.

> **ESTIMATE** 2

### Acceptance Criteria

```gherkin
Scenario: When a user clicks on a result within a dictionary search to take them to a definition page, an analytics click event will be fired.
  Given "audience" is set to "Patient"
    And "dictionaryTitle" is set to "NCI Dictionary of Cancer Terms"
    And "dictionaryName" is set to "Cancer.gov"
    And "language" is set to "en"
    And "baseHost" is set to "http://localhost:3000"
    And "canonicalHost" is set to "https://www.cancer.gov"
    And "siteName" is set to "National Cancer Institute"
    And "channel" is set to "Publications"
    And "publishedDate" is set to "02/02/2011"
    And NCIDataLayer is being captured 
  When user is searching "startsWith" for the term "meta"
    And user selects the third result
  Then there should be an NCIDataLayer Other event with the name "GlossaryApp:Other:ResultClick" and linkname "TermsDictionaryResults"
    And the event has the following data
      | key           | value |
      | resultIndex        | 3 |
      | resultIdOrName | metabolic-acidosis |
      | resultName | metabolic acidosis |
```

```gherkin
Scenario: When a user clicks on a result within a dictionary search to take them to a definition page, an analytics click event will be fired.
  Given "audience" is set to "Patient"
    And "dictionaryTitle" is set to "NCI Dictionary of Cancer Terms"
    And "dictionaryName" is set to "Cancer.gov"
    And "language" is set to "en"
    And "baseHost" is set to "http://localhost:3000"
    And "canonicalHost" is set to "https://www.cancer.gov"
    And "siteName" is set to "National Cancer Institute"
    And "channel" is set to "Publications"
    And "publishedDate" is set to "02/02/2011"
    And NCIDataLayer is being captured 
  When user is searching "startsWith" for the term "meta"
    And user selects the fourth result
  Then there should be an NCIDataLayer Other event with the name "GlossaryApp:Other:ResultClick" and linkname "TermsDictionaryResults"
    And the event has the following data
      | key           | value |
      | resultIndex        | 4 |
      | resultIdOrName | 44055 |
      | resultName | metabolic disorder |
```

```gherkin
Add a test for expand as well...
```

### Resources:
* Feature: https://tracker.nci.nih.gov/browse/CGOVWCMS-30

### Notes

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Identify how to capture analytics for a test

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by bryanpizzillo** [comment]
Original AC
```gherkin
Scenario: When a user clicks on a result within a dictionary search to take them to a definition page, an analytics click event will be fired.
  Given user has clicked on a term from search results
    Then standard click events values are fired:
        - Channel: Publications 
        - PageName: This should be the "www.cancer.gov" + the URL path for the definition. Try to define this in a similar way as to how it is done on the rest of the site.       
        - Prop8/evar2: Captures "english" or "spanish" depending on language of page.
        - Prop4 = "D=pev1"   (This gets set in Adobe to the evar1 value stored in the cookie from the page load call.)
        - Prop67 = "D=pageName"   (This gets set in Adobe to the pageName value stored in the cookie from the page load call.) 
      And these specific values will be included: 
        - Prop13: number of result clicked on the page  
        - Event42 
```
