### ISSUE TITLE
Enabler: Implement React App Tooling

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/glossary-app#27]
# Implement React App Tooling

We need to test out a number of things in order to setup a react app repo for our dev processes. WORK should be first prototyped and validated against the cgov-react-app-playground before integrations with the app are made.

> **ESTIMATE** xx

### Resources:
* Sandbox Repo: https://github.com/NCIOCPL/cgov-react-app-playground

### Sub-Tasks
- [x] Implement npm caching in github workflow
- [x] Implement cypress test running in github workflow
- [x] Output code coverage reports as an artifact of the build process

**Comment by arcepaul** [comment]
npm caching has been added to the workflow and is confirmed working in the sandbox app.  Also setup`npm test` such that it executes both jest and cypress and merges coverage reports to create a single artifact that can be uploaded later.
