### ISSUE TITLE
Story: Audio Pronunciation Player on Term Page

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/glossary-app#28]
## As a user, I want to hear how a term is pronounced, so that I may be able to pronounce it correctly when talking with others

> **ESTIMATE** 2

### Acceptance Criteria

```gherkin
Scenario: Able to play the pronunciation on a term page
  Given the user is viewing the definition with the pretty url "metastatic"
    And there is an audio player with the url "https://nci-media-dev.cancer.gov/pdq/media/audio/704104.mp3" before the phonetic spelling
  When the user clicks the audio speaker icon
  Then the pronunciation for metastatic should play
  And a pause button appears in place of the speaker icon
  When user clicks pause
  Then the audio track pauses and the play icon appears
  When user clicks play icon
  Then audio plays from where it was paused and the pause icon appears
  And when audio has finished playing, the button returns to the audio speaker icon
```
```gherkin
Scenario: No pronunciation to play on a term page
  Given the user is viewing the definition with the pretty url "hpv"
  Then there is no audio player or icon
```
 ```gherkin
Scenario: As a screen reader, I would like to hear the accessible text associated with the audio player
  Given the page is in English and the screen reader is reading the page
  Then play the accessible text, "Listen to pronunciation",  when target gets to the audio icon. 
```
```gherkin
Scenario: As a screen reader, I would like to hear the accessible text associated with the audio player
  Given the page is in Spanish and the screen reader is reading the page
  Then play the accessible text, "Escuche la pronunciación",  when target gets to the audio icon. 
```

### Resources:
* Comp: https://publicis.invisionapp.com/share/HZVRID6RSJ7#/screens
* Existing Web Pages:
   * https://www.cancer.gov/publications/dictionaries/cancer-terms/def/metastatic
   * https://www.cancer.gov/publications/dictionaries/cancer-terms/def/hpv

---

### Prerequisites
- [x] Spike: Identify accessible Audio Player #23

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
@mworrest @blilianyu - please add acceptance criteria for the accessible text for English and Spanish.  Thank you!
