### ISSUE TITLE
Story: Media on Term Page

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/glossary-app#29]
## As a user, I want to view one or more media items related to a term, so that I may gain a deeper understanding of the term and its definition

> **ESTIMATE** 3

#### Image in English & Spanish
```gherkin

Scenario Outline : View a term with a single image and click enlarge
  Given the user is viewing the definition with the pretty url "lung-cancer"
     And an image is displayed with the source "https://nci-media-dev.cancer.gov/pdq/media/images/466533-571.jpg" and alt text "Respiratory anatomy; drawing shows right lung with upper, middle, and lower lobes; left lung with upper and lower lobes; and the trachea, bronchi, lymph nodes, and diaphragm. Inset shows bronchioles, alveoli, artery, and vein." and caption "Anatomy of the respiratory system, showing the trachea and both lungs and their lobes and airways. Lymph nodes and the diaphragm are also shown. Oxygen is inhaled into the lungs and passes through the thin membranes of the alveoli and into the bloodstream (see inset)." using the "<TEMPLATE_HERE>" class
     And there is an link with the href "https://nci-media-dev.cancer.gov/pdq/media/images/466533.jpg" and text "Enlarge"
  When the user clicks the link with the href "https://nci-media-dev.cancer.gov/pdq/media/images/466533.jpg"
  Then a window is opened in a new tab with the url "https://nci-media-dev.cancer.gov/pdq/media/images/466533.jpg"
```

```gherkin

Scenario Outline : View a Spanish term with a single image and click enlarge
  Given the user is viewing the spanish definition with the pretty url "cancer-de-pulmon"
     And an image is displayed with the source "https://nci-media-dev.cancer.gov/pdq/media/images/466537-571.jpg"
     And there is an link with the href "https://nci-media-dev.cancer.gov/pdq/media/images/466537.jpg" and text "Ampliar"
  When the user clicks the link with the href "https://nci-media-dev.cancer.gov/pdq/media/images/466537.jpg"
  Then a window is opened in a new tab with the url "https://nci-media-dev.cancer.gov/pdq/media/images/466537.jpg"
```

#### Video
```gherkin
Scenario Outline : View a term with a single image and click enlarge
  Given the user is viewing the definition with the pretty url "metastatic"
     And a youtube video is displayed with the video id "fQwar_-QdiQ" and title "Metastasis: How Cancer Spreads" and caption "Many cancer deaths are caused when cancer moves from the original tumor and spreads to other tissues and organs. This is called metastatic cancer. This animation shows how cancer cells travel from the place in the body where they first formed to other parts of the body." using the "<TEMPLATE_HERE>" class
     And there is a play button
  When the user clicks the play button
  Then the video beings playing
```
> **_NOTE:_** I cannot see any text that would make the player English vs Spanish, but we should test.

#### Media counting and ordering

```gherkin
Scenario: View a term without media
  Given the user is viewing the definition with the pretty url "hpv"
  Then the term is displayed without error
```
```gherkin
Scenario: View a term with image and video
  Given the user is viewing the definition with the pretty url "metastasis"
  Then an image is displayed with the source "https://nci-media-dev.cancer.gov/pdq/media/images/764135-571.jpg" using the "<TEMPLATE_HERE>" class
     And a youtube video is displayed with the video id "fQwar_-QdiQ" using the "<TEMPLATE_HERE>" class
```

### Resources:
* Glossary API Model: https://github.com/NCIOCPL/glossary-api/wiki/Glossary
   * This story involves displaying the (I) Media, (C) Image and (C) Video objects
* Existing Web Pages:
   * With No Media: https://www.cancer.gov/publications/dictionaries/cancer-terms/def/hpv
   * With Single Image: https://www.cancer.gov/publications/dictionaries/cancer-terms/def/lung-cancer
   * With Multiple Images: https://www.cancer.gov/publications/dictionaries/cancer-terms/def/stage-iv-esophageal-squamous-cell-carcinoma
      * This one has a slightly odd presentation and is a specific use case WRT displaying 2 images for Stage IVA and one for Stage IVB and trying to keep them separated.
   * One Video: There is no live example?
   * With One Image and One Video: https://www.cancer.gov/publications/dictionaries/cancer-terms/def/metastasis
   

### Notes
* A term can have one or more media items associated with it. They appear in the order returned by the API.
* Media item types are currently image and video, but we plan to have more in the future.
* Currently the enlarge url is the 750 sized image. The current PDQ summaries use the "original" sized image. Changing the requirements to meet PDQ summaries.
* The markup for the images and media *should* match up to the same structures as the cgov-digital-platform images and videos.
---

### Prerequisites
- [x] Implement a media player (#45)
- [x] Basic Term page (#15)
### Tasks
- [x] Create component for cgov image
- [x] Create component for cgov video
- [x] e2e tests

### Technical Notes
- More notes, or technical nuances/direction
