### ISSUE TITLE
Story: Metadata on Term Definition

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/glossary-app#30]
## As a user, I want metadata on the page, so that I can share the web page to social media services correctly

> **ESTIMATE** 3

### Acceptance Criteria

```gherkin
Scenario: View basic term metadata
  Given the user is viewing the definition with the pretty url "metastatic"
  When the dictionary title is "NCI Dictionary of Cancer Terms"
     And the site name is "National Cancer Institute"
     And the dictionary language is "en"
     And the dictionary name is "Cancer.gov"
     And the canonical host is "https://www.cancer.gov"
     And the base host is "http://localhost:3000"
     And the base path is ""
     And the Spanish language basepath is "espanol/publicaciones/diccionario" 
  Then the title tag should be "Definition of metastatic - NCI Dictionary of Cancer Terms - National Cancer Institute" 
    And there is a meta tag with a property "og:title" and content "Definition of metastatic - NCI Dictionary of Cancer Terms"
    And there is a meta tag with a property "og:url" and content "http://localhost:3000/def/metastatic"
    And there is a link tag with rel "canonical" and href  "https://www.cancer.gov/def/metastatic"
    And there is a link tag with rel "alternate" and hreflang "en" and href  "http://localhost:3000/def/metastatic"
    And there is a link tag with rel "alternate" and hreflang "es" and href "http://localhost:3000/espanol/publicaciones/diccionario/def/metastasico"

```

```gherkin
Scenario: View basic term metadata in Spanish
  Given the user is viewing the definition with the pretty url "metastasico"
  When the dictionary name is "Diccionario de cáncer"
     And the site name is "Instituto Nacional del Cáncer"
     And the dictionary language is "es"
     And the dictionary name is "Cancer.gov"
     And the canonical base is "https://www.cancer.gov"
     And the base url is "http://localhost:3000"
     And the base path is ""
     And the English language basepath is "/publications/dictionaries/cancer-terms" 
  Then the title tag should be "Definición de metastásico - Diccionario de cáncer - Instituto Nacional del Cáncer" 
    And there is a meta tag with a property "og:title" and content "Definición de metastásico - Diccionario de cáncer"
    And there is a meta tag with a property "og:url" and content "http://localhost:3000/def/metastatic"
    And there is a link tag with rel "canonical" and href  "https://www.cancer.gov/def/metastatic"
    And there is a link tag with rel "alternate" and hreflang "es" and href  "http://localhost:3000/def/metastatic"
    And there is a link tag with rel "alternate" and hreflang "en" and href "http://localhost:3000/publications/dictionaries/cancer-terms/def/metastasico"
```
```gherkin
Scenario: View page works when there translated defs in an untranslated app
  Given the user is viewing the definition with the pretty url "metastatic"
  When the dictionary title is "NCI Dictionary of Cancer Terms"
     And the site name is "National Cancer Institute"
     And the dictionary language is "en"
     And the dictionary name is "Cancer.gov"
     And the canonical base is "https://www.cancer.gov/publications/dictionaries/cancer-terms"
     And the base url is "http://localhost:3000/"
     And there are no language bases 
  Then the page should load
    And there are no link tag with rel "alternate"
```

```gherkin
Scenario: Term meta descriptions over two sentences truncated after two sentences
  Given the user is viewing the definition with the pretty url "hpv"
  Then a meta tag with a name of "description" and content "A type of virus that can cause abnormal tissue growth (for example, warts) and other changes to cells. Infection for a long time with certain types of HPV can cause cervical cancer." appears on the page
    And a meta tag with a property of "og:description" and content "A type of virus that can cause abnormal tissue growth (for example, warts) and other changes to cells. Infection for a long time with certain types of HPV can cause cervical cancer." appears on the page

Scenario: Term meta descriptions UNDER two sentences are displayed in full
  Given the user is viewing the definition with the pretty url "metastatic"
  Then a meta tag with a name of "description" and content "Having to do with metastasis, which is the spread of cancer from the primary site (place where it started) to other places in the body." appears on the page
    And a meta tag with a property of "og:description" and content "Having to do with metastasis, which is the spread of cancer from the primary site (place where it started) to other places in the body." appears on the page
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

* The meta description and og:description tags display the first 2 sentences of the definition.

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Add tags to Basic Term Page
- [ ] Split up description into a max of 2 sentences
- [ ] Take in the Spanish base URL (initialize parameter from CGov Digital Platform)
- [ ] Create steps/phrases 

### Technical Notes
- The current app uses the following regex for splitting up the sentences, `/(?<=[\.!\?])\s+/`. NOTE: it is a C# regex, so it may not port exactly...
- We discussed how to determine the "Spanish language base" for a given dictionary. The two approaches were:
    1. Pass in a dictionary that had language code & the base url of that dictionary.
    2. Leverage the <link hreflang rel="alternate"> tags that will be produced by Drupal on the Dictionary of Cancer Terms and the Diccionario de cáncer pages. The `initialize()` function will have some way of accepting the language bases...
