### ISSUE TITLE
Implement step definitions

### ISSUE THREAD

**Issue by kate-mashkina** [NCIOCPL/glossary-app#37]
### Step definitions featured below will need to be implemented in Cypress /common folder

- [x] **Given ‘the user is viewing the definition with the pretty url {string}’, (a)**
_It’s taking the user to the base url + a string_

- [ ] **Then ('there is a heading on the page with {string}’,(a))**
_This step is for element ‘More Information’ – get element, retrieve it’s text and assert two strings_
 - [x] **Then ‘there is no text on the page with More Information’**
_Assert that ‘More Infromation’ element Is not present_
- [ ] **Then ‘there is a link to {string} with the text {string}’,(a,b)**
_Assert one of  “more information” links href attr and it’s text equal to provided strings_
- [ ] **Then ‘there is a link to a definition with the pretty url {string} and the text {string} following the text {string}’, (a,b,c)**
_Pretty url =a, link text = b, ‘definition of’ text  = c, get all three elements and assert equality of strings_
- [x] **Then the page title is {string}**
_First H1 tag in the DOM_
- [x] **Then the pronunciation text {string} appears on the page**
_Transcription of word’s pronunciation_
- [x] **Then the definition text {string} appears on the page**
_Definition of the term (blob of text)_
- [x] **Then the pronunciation text does not appear on the page**
_Assert absence of transcription of the term_
- [x] **Then {string} page is loaded**
_This step needs to pull page’s url and assert that path is equal to {string}_

**Parent Issue:** #9999

### Sub-Tasks
- [ ] 

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by bryanpizzillo** [comment]
@kate-mashkina I am closing this as you have been building them out as part of the stories.
