### ISSUE TITLE
Story: Term Page - Search Box Display

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/glossary-app#43]
## As a user, I would like the option to search for another term while on a term page so I don't have to navigate back to the dictionary landing page.

> **ESTIMATE** 2

### Acceptance Criteria

```gherkin
Scenario: As a user, I would like to see an option to search when I am viewing the definition for a term
  Given the user is viewing the definition with the pretty url "metastatic"
  Then heading "Search NCI's Dictionary of Cancer Terms" appears
  Then search options for "Starts with" and "Contains" appears
  Then "keywords" search box appears
  Then search button appears beside search box with "Search"
  Then "Browse:" appears with A-Z List of Links beside it
  And user submits their search 
  Then the system returns users to the search results page for the search term
```

```gherkin
Scenario: As a user, I would like to see an option to browse the A-Z list when I am viewing the definition for a term
  Given the user is viewing the definition with the pretty url "metastatic"
  Then heading "Search NCI's Dictionary of Cancer Terms" appears
  Then search options for "Starts with" and "Contains" appears
  Then "keywords" search box with "Escribir frase o palabra" appears
  Then search button appears beside search box with "Search"
  Then "Browse:" appears with A-Z List of Links beside it
  When user clicks a letter in the A-Z list 
  Then the system returns users to the search results page for the letter
```

```gherkin
Background:
    Given "language" is set to "es"
Scenario: As a user, I would like to see an option to search when I am viewing the definition for a term in Spanish
  Given the user is viewing the definition with the pretty url "metastasico"
  Then heading "Buscar en el Diccionario de cáncer" appears
  Then search options for "Empieza con" and "Contiene" appears
  Then "keywords" search box appears
  Then search button appears beside search box with "Buscar"
  Then "Navegar por letra inicial:" appears with A-Z List of Links beside it
  And user submits their search 
  Then the system returns users to the search results page for the search term
```

```gherkin
Background:
    Given "language" is set to "es"
Scenario: As a user, I would like to see an option to browse the A-Z list when I am viewing the definition for a term in Spanish
Given the user is viewing the definition with the pretty url "metastasico"
  Then heading "Buscar en el Diccionario de cáncer" appears
  Then search options for "Empieza con" and "Contiene" appears
  Then "keywords" search box appears
  Then search button appears beside search box with "Buscar"
  Then "Navegar por letra inicial:" appears with A-Z List of Links beside it
  When user clicks a letter in the A-Z list 
  Then the system returns users to the search results page for the letter
```
```gherkin
Scenario: User can execute search by hitting the Enter key 
  Given user is on landing Cancer Terms page 
  When user starts typing “cancer”  in the search bar 
  Then placeholder text disappears  
  When user hits Enter key
    Then Search is executed  
  Then the system returns users to the search results page for the search term (URL has /search)
```

```gherkin
Scenario: User can execute search by hitting the Enter key 
  Given user is on landing Cancer Terms page 
    And user selects "Contains"
    And user types search keywords in the search bar 
  Then placeholder text disappears  
  When user hits Enter key
    Then Search is executed  
  Then the system returns users to the search results page for the search term (URL has /search)
```

```gherkin
Background
  Given "language" is set to "es"
Scenario: User can execute search by hitting the Enter key 
  Given user is on Spanish landing Cancer Terms page 
    And user selects "Contiene"
    And user types search keywords in the search bar 
  Then placeholder text disappears  
  When user hits Enter key
    Then Search is executed  
  Then the system returns users to the search results page for the search term (URL has /buscar)
```

### Resources:
* Mockups: https://publicis.invisionapp.com/share/HZVRID6RSJ7#/screens/402838500
* Web Page: https://www.cancer.gov/publications/dictionaries/cancer-terms/def/metastasis

### Notes
* Since we will have multiple titles based on whichever dictionary is being viewed, and Spanish is complicated we will need to make it so that we pass in the text above the search bar to the initialization of the app. 
---

### Prerequisites
- [x] Basic Term Page view has been built (#15)
- [x] Basic Search Box has been built (#76)
- [x] A-Z list has been built (#76)
- [x] Starts With and Contains buttons have been built (first round - no autosuggest) (#76)

### Tasks
- [ ] Add SearchBox to Basic Term Page (#86)
- [ ] Add integration tests

### Technical Notes
- More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
@VictoriaSunNIH - need to fill this one out
