### ISSUE TITLE
Enabler: Implement Accessible Media Player

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/glossary-app#45]
# Implement Accessible Media Player (for video and audio players)

Is an all-encompassing media player needed to handle the use cases for the dictionaries or should it just be broken up into different components.

> **ESTIMATE** 5

### Resources:
* Feature: JIRA Ticket #
* Mockups: https://publicis.invisionapp.com/share/HZVRID6RSJ7#/screens
* References: https://www.cancer.gov/publications/dictionaries/cancer-terms/def/metastatic

### Prerequisites
- [x] identify places and what types of media are needed

### Subtasks
- [x] create pronunciation audio player component using HTML5 audio api
- [x] port video implementation from cgov platform

### Notes

* Evaluate and implement an accessible media player
  * Should jive with screenreaders
  * keyboard accessible
  * possibly support youtube playback
