### ISSUE TITLE
Enabler: Setup netstorage for serving out built artifacts

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/glossary-app#48]
# Title of Enabler

*Description of what is to be accomplished.*
*Examples:*
* *Initial Setup of Dev Tier*
* *Create Application Framework*
* *Define Unit Test Approach*
* *Research UX Patterns for Search*

> **ESTIMATE** 20

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* References: *URL to web site with examples*
* Web Page: *Here goes a URL to an existing web page*

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Sub-Tasks
- [ ] Setup netstorage for serving out built artifacts #48
   - [ x ] Setup netstorage
   - [ x ] Prototype uploading to netstorage
   - [ x ] Setup react-app-dev.cancer.gov property for serving out react apps for pull requests
   - [ x ] Prototype multiple react app routes so that we may test our react-app-dev.cancer.gov / netstorage property.
   - [ ] Resolve any url rewriting issues due to multi route issues
   - [ ] Identify (and resolve) any cache clearing issues when re-uploading the same artifact file
- [ ] Integrate netstorage uploads in github workflow
       * This should occur for pushes and pull requests to the NCIOCPL repos, it should NOT occur on 
### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction
