### ISSUE TITLE
Create Definition View component

### ISSUE THREAD

**Issue by seyilonge-nci** [NCIOCPL/glossary-app#61]
Display the term, optional pronunciation and definition, and CDR ID Data Element on the page + component tests

**Parent Issue:** #15 

### Sub-Tasks
- [x] Create Definition View (Added as part of #53)
- [x] Add Route (Added as #53)
- [x] Create stubbed hook to get term (returning mocks) 
- [x] Add Display term, optional pronunciation and definition to Definition View
- [x] Add styling for component
- [x] Add CDR ID Data element
- [x] Update Definition View Component test

### Notes
Added stubbed data for display purpose to `Definition` component (this would be eventually swapped out with the actual API call)
