### ISSUE TITLE
Fetch term definition from the API

### ISSUE THREAD

**Issue by seyilonge-nci** [NCIOCPL/glossary-app#65]
Fetch term definition from API and display results fetched in `Definition` component

**Parent Issue:** #15 

### Sub-Tasks
- [x] Create custom axios hook (integrated `react-fetching-library` instead)
- [x] Create action `getTermDefinition` to retrieve definition from API (write unit tests)
- [x] Dispatch action from effect in `Definition` component to fetch term definition (update component test as needed)
- [ ] Wire axios call to mocks for dev and E2E tests

### Notes

* How are we handling display when an error occurs on a fetch?
* For production and `react-app-dev.cancer.gov ( playground environment )` the `dictionaryEndpoint` is set to the actual api endpoint `https://webapis-dev.cancer.gov/glossary/v1/` through the `initialize` function, and for other non-prod environments `dictionaryEndpoint` is set to `/api` which will use mocked data
