### ISSUE TITLE
Enabler: Ability to view other dictionaries

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/glossary-app#74]
## As a reviewer of the system, I need to be able to view the different dictionary sources when on react-app-dev on the front-end, so that i can browse all the dictionaries and verify their functionality.

> **ESTIMATE** 3

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] #75 - Index.html variables

### Sub-Tasks
- [x] Modify webpack config (entrypoints and modules)
- [x] Create dictionary selector to appear on lower tiers

### Notes
Three different dictionaries:
Cancer Terms, Cancer terms(spanish), Genetics

**Comment by arcepaul** [comment]
closed by PR #100 .
