### ISSUE TITLE
Add SearchBox to Basic Term Page

### ISSUE THREAD

**Issue by seyilonge-nci** [NCIOCPL/glossary-app#86]
Include `SearchBox` component on Basic Term page

**Parent Issue:** #43 

### Sub-Tasks
- [x] Add `SearchBox` component
- [x] Update tests for Basic Term page
- [x] Add title to `SearchBox` component (would only show in Basic Term page display context)

### Notes
