### ISSUE TITLE
Enabler: Term Count Placeholder for Intro Text

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/glossary-app#97]
# TBD

Just the front-end portion of putting the term count placeholder in place in the intro text - passed in through the initialize (endpoint for count already exists in API).

Support transforming:

```
"The NCI Dictionary of Cancer Terms features ${term_count} terms related to cancer and medicine.

We offer a widget that you can add to your website to let users look up cancer-related terms. Get NCI’s Dictionary of Cancer Terms Widget."

```
To:

```
The NCI Dictionary of Cancer Terms features 8,531 terms related to cancer and medicine.

We offer a widget that you can add to your website to let users look up cancer-related terms. Get NCI’s Dictionary of Cancer Terms Widget.

```
Examples:

*Examples:*
* *Initial Setup of Dev Tier*
* *Create Application Framework*
* *Define Unit Test Approach*
* *Research UX Patterns for Search*

> **ESTIMATE** 2

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* References: *URL to web site with examples*
* Web Page: *Here goes a URL to an existing web page*

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Sub-Tasks

- [x] Create a method to replace any number of tokens in the given string and return modified string
- [x] Util to convert given number to thousands format

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction
